# Generated by Django 5.0.4 on 2024-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("contactno", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=30)),
            ],
        ),
    ]
